Last login: Sat May 17 08:23:06 on ttys013
(base) abhisheksenapati@Mac ~ % CD
(base) abhisheksenapati@Mac ~ % cd
(base) abhisheksenapati@Mac ~ % 
(base) abhisheksenapati@Mac ~ % 
(base) abhisheksenapati@Mac ~ % 
(base) abhisheksenapati@Mac ~ % 
(base) abhisheksenapati@Mac ~ % 
(base) abhisheksenapati@Mac ~ % ---------
zsh: command not found: ---------
(base) abhisheksenapati@Mac ~ % conda activate ds_env
(ds_env) abhisheksenapati@Mac ~ % cd /Users/abhisheksenapati/Desktop/Deployment/car_insurance_app
(ds_env) abhisheksenapati@Mac car_insurance_app %  
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % ls
app.py				static
carinsurance_xgb_clas.pkl	templates
preprocessor.pkl
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % 
(ds_env) abhisheksenapati@Mac car_insurance_app % python app.py
/opt/anaconda3/envs/ds_env/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [09:15:22] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1744329043786/work/src/gbm/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
/opt/anaconda3/envs/ds_env/lib/python3.9/site-packages/xgboost/core.py:158: UserWarning: [09:15:22] WARNING: /Users/runner/miniforge3/conda-bld/xgboost-split_1744329043786/work/src/gbm/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)
 * Debugger is active!
 * Debugger PIN: 106-885-602
127.0.0.1 - - [17/May/2025 09:15:29] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [17/May/2025 09:15:29] "GET /static/back.png HTTP/1.1" 304 -
127.0.0.1 - - [17/May/2025 09:15:30] "GET /favicon.ico HTTP/1.1" 404 -

